[package]
name = "grrs"
version = "0.1.0"
authors = ["Oriol Barcelona <oriol.barcelona@dynatrace.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
